// src/dummyEvents.js
const dummyEvents = [
	{
		id: 1,
		name: "Tech Conference 2024",
		venue: "Convention Center, City A",
		details: "A conference on the latest in tech.",
		maxCapacity: 500,
	},
	{
		id: 2,
		name: "Music Festival",
		venue: "Open Grounds, City B",
		details: "A weekend of music and fun.",
		maxCapacity: 1000,
	},
	{
		id: 3,
		name: "Art Exhibition",
		venue: "Art Gallery, City C",
		details: "Showcasing the best in modern art.",
		maxCapacity: 200,
	},
	// Add 17 more events
	{
		id: 4,
		name: "Book Fair",
		venue: "Exhibition Hall, City D",
		details: "A fair for book enthusiasts.",
		maxCapacity: 300,
	},
	{
		id: 5,
		name: "Food Festival",
		venue: "Park, City E",
		details: "A celebration of food and culture.",
		maxCapacity: 800,
	},
	{
		id: 6,
		name: "Film Festival",
		venue: "Cinema Hall, City F",
		details: "Screening of independent films.",
		maxCapacity: 400,
	},
	{
		id: 7,
		name: "Startup Meetup",
		venue: "Tech Park, City G",
		details: "Networking for startups and investors.",
		maxCapacity: 250,
	},
	{
		id: 8,
		name: "Gaming Convention",
		venue: "Convention Center, City H",
		details: "A convention for gaming enthusiasts.",
		maxCapacity: 600,
	},
	{
		id: 9,
		name: "Dance Workshop",
		venue: "Dance Studio, City I",
		details: "Learn the latest dance moves.",
		maxCapacity: 150,
	},
	{
		id: 10,
		name: "Marathon",
		venue: "City Streets, City J",
		details: "A marathon for all age groups.",
		maxCapacity: 2000,
	},
	{
		id: 11,
		name: "Yoga Retreat",
		venue: "Resort, City K",
		details: "A retreat to rejuvenate your mind and body.",
		maxCapacity: 100,
	},
	{
		id: 12,
		name: "Photography Workshop",
		venue: "Studio, City L",
		details: "Learn the art of photography.",
		maxCapacity: 50,
	},
	{
		id: 13,
		name: "Coding Bootcamp",
		venue: "Tech Hub, City M",
		details: "An intensive coding bootcamp.",
		maxCapacity: 200,
	},
	{
		id: 14,
		name: "Fashion Show",
		venue: "Hotel Ballroom, City N",
		details: "A showcase of the latest fashion trends.",
		maxCapacity: 300,
	},
	{
		id: 15,
		name: "Health Expo",
		venue: "Expo Center, City O",
		details: "An expo on health and wellness.",
		maxCapacity: 700,
	},
	{
		id: 16,
		name: "Gardening Workshop",
		venue: "Community Center, City P",
		details: "Learn how to start your own garden.",
		maxCapacity: 50,
	},
	{
		id: 17,
		name: "Robotics Competition",
		venue: "University Hall, City Q",
		details: "A competition for robotics enthusiasts.",
		maxCapacity: 400,
	},
	{
		id: 18,
		name: "Wine Tasting",
		venue: "Vineyard, City R",
		details: "A tasting of the finest wines.",
		maxCapacity: 100,
	},
	{
		id: 19,
		name: "Meditation Session",
		venue: "Yoga Center, City S",
		details: "A session to meditate and relax.",
		maxCapacity: 100,
	},
	{
		id: 20,
		name: "Hiking Trip",
		venue: "Mountain Trails, City T",
		details: "A trip for hiking enthusiasts.",
		maxCapacity: 60,
	},
];

export default dummyEvents;
